"Filed out from Dolphin Smalltalk 7"!

Estrategia subclass: #CpuArriesgado
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CpuArriesgado guid: (GUID fromString: '{6390F450-3515-4436-B93E-586D112D91A8}')!
CpuArriesgado comment: ''!
!CpuArriesgado categoriesForClass!MVP-Models! !
!CpuArriesgado methodsFor!

jugar: unaPartida!

pedir: unaCarta!

plantarse: unaPartida! !
!CpuArriesgado categoriesFor: #jugar:!public! !
!CpuArriesgado categoriesFor: #pedir:!public! !
!CpuArriesgado categoriesFor: #plantarse:!public! !

