"Filed out from Dolphin Smalltalk 7"!

Model subclass: #Estrategia
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Estrategia guid: (GUID fromString: '{13FB2A18-19DF-44CE-A178-EFB2D5EE5455}')!
Estrategia comment: ''!
!Estrategia categoriesForClass!MVP-Models! !
!Estrategia methodsFor!

jugar: unaPartida
! !
!Estrategia categoriesFor: #jugar:!public! !

