"Filed out from Dolphin Smalltalk 7"!

Model subclass: #Carta
	instanceVariableNames: 'palo valor imagen'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Carta guid: (GUID fromString: '{5F36A82D-3B3F-4694-A9A6-8C43C5748EBE}')!
Carta comment: ''!
!Carta categoriesForClass!Unclassified! !
!Carta methodsFor!

imagen
	^imagen!

imagen: anObject
	imagen := anObject!

palo
	^palo!

palo: anObject
	palo := anObject!

valor
	^valor!

valor: anObject
	valor := anObject! !
!Carta categoriesFor: #imagen!accessing!private! !
!Carta categoriesFor: #imagen:!accessing!private! !
!Carta categoriesFor: #palo!accessing!private! !
!Carta categoriesFor: #palo:!accessing!private! !
!Carta categoriesFor: #valor!accessing!private! !
!Carta categoriesFor: #valor:!accessing!private! !

