"Filed out from Dolphin Smalltalk 7"!

Estrategia subclass: #CpuPrudente
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CpuPrudente guid: (GUID fromString: '{3C8B817B-547F-4DAE-B576-088C36CE1E5F}')!
CpuPrudente comment: ''!
!CpuPrudente categoriesForClass!MVP-Models! !
!CpuPrudente methodsFor!

jugar: unaPartida!

pedir: unaCarta!

plantarse: unaPartida
! !
!CpuPrudente categoriesFor: #jugar:!public! !
!CpuPrudente categoriesFor: #pedir:!public! !
!CpuPrudente categoriesFor: #plantarse:!public! !

