"Filed out from Dolphin Smalltalk 7"!

Estrategia subclass: #Humano
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Humano guid: (GUID fromString: '{A1596464-7EA2-4B31-BA8D-52CD76C94AF7}')!
Humano comment: ''!
!Humano categoriesForClass!MVP-Models! !
!Humano methodsFor!

jugar: unaPartida
!

pedir: unaCarta!

plantarse: unaPartida! !
!Humano categoriesFor: #jugar:!public! !
!Humano categoriesFor: #pedir:!public! !
!Humano categoriesFor: #plantarse:!public! !

