"Filed out from Dolphin Smalltalk 7"!

Model subclass: #Partida
	instanceVariableNames: 'jugadores banca cartas'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Partida guid: (GUID fromString: '{D0212CD8-AA07-4BB4-92D1-640495C233DA}')!
Partida comment: ''!
!Partida categoriesForClass!MVP-Models! !
!Partida methodsFor!

banca
	^banca!

banca: anObject
	banca := anObject!

cargarPartida!

cartas
	^cartas!

cartas: anObject
	cartas := anObject!

finalizar!

guardarPartida!

jugadores
	^jugadores!

jugadores: anObject
	jugadores := anObject!

mezclar!

repartir! !
!Partida categoriesFor: #banca!accessing!public! !
!Partida categoriesFor: #banca:!accessing!public! !
!Partida categoriesFor: #cargarPartida!public! !
!Partida categoriesFor: #cartas!accessing!public! !
!Partida categoriesFor: #cartas:!accessing!public! !
!Partida categoriesFor: #finalizar!public! !
!Partida categoriesFor: #guardarPartida!public! !
!Partida categoriesFor: #jugadores!accessing!public! !
!Partida categoriesFor: #jugadores:!accessing!public! !
!Partida categoriesFor: #mezclar!public! !
!Partida categoriesFor: #repartir!public! !

