"Filed out from Dolphin Smalltalk 7"!

Estrategia subclass: #NoDisponible
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
NoDisponible guid: (GUID fromString: '{895E6D34-BA9B-4B5B-9B28-80BE8ABBDDF5}')!
NoDisponible comment: ''!
!NoDisponible categoriesForClass!MVP-Models! !
!NoDisponible methodsFor!

jugar: unJugador con: unaPartida
	"No juega :)"

	! !
!NoDisponible categoriesFor: #jugar:con:!public! !

